env:
  TERM: xterm-256color

window:
  opacity: 0.9
  dynamic_padding: true
  decorations: full
  title: Alacritty
  class:
    instance: Alacritty
    general: Alacritty
  decorations_theme_variant: Dark

scrolling:
  history: 10000
  multiplier: 3

font:
  size: 16
  normal:
    family: "FantasqueSansMono Nerd Font"
  bold:
    family: "FantasqueSansMono Nerd Font"
  italic:
    family: "FantasqueSansMono Nerd Font"
  bold_italic:
    family: "FantasqueSansMono Nerd Font"
    size: 10.0

draw_bold_text_with_bright_colors: true

save_to_clipboard: true

window.dynamic_title: true

cursor:
  style: Beam

live_config_reload: true

shell:
  program: /usr/bin/fish

mouse:
  hide_when_typing: true

mouse_bindings:
  - { mouse: Right, action: PasteSelection }

key_bindings:
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: C, mods: Control|Shift, action: Copy }
  - { key: Insert, mods: Shift, action: PasteSelection }
  - { key: Key0, mods: Control, action: ResetFontSize }
  - { key: Equals, mods: Control, action: IncreaseFontSize }
  - { key: Plus, mods: Control, action: IncreaseFontSize }
  - { key: Minus, mods: Control, action: DecreaseFontSize }
  - { key: Minus, mods: Control, action: DecreaseFontSize }

import:
  - ~/.config/alacritty/colors.yml
