import = ["/home/astrogoat/.config/alacritty/colors.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.bold]
family = "FantasqueSansMono Nerd Font"

[font.bold_italic]
family = "FantasqueSansMono Nerd Font"

[font.italic]
family = "FantasqueSansMono Nerd Font"

[font.normal]
family = "FantasqueSansMono Nerd Font"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Right"

[scrolling]
history = 10000
multiplier = 3

[shell]
program = "/usr/bin/fish"

[window]
decorations = "full"
decorations_theme_variant = "Dark"
dynamic_padding = true
opacity = 0.9
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"
