colors:
  primary:
    background: '#11100f'
    foreground: '#f4e7a7'
  normal:
    black: '#11100f'
    red: '#9B675B'
    green: '#997E6B'
    yellow: '#E26256'
    blue: '#F29922'
    magenta: '#CAB04C'
    cyan: '#ECA05D'
    white: '#f4e7a7'
  bright:
    black: '#aaa174'
    red: '#c98576'
    green: '#c6a38b'
    yellow: '#ff7f6f'
    blue: '#ffc62c'
    magenta: '#ffe462'
    cyan: '#ffd078'
    white: '#ffffd9'
