#!/usr/bin/env python3

from qutescript import userscript
from bs4 import BeautifulSoup
from lxml import etree

@userscript
def main(request):
    with open(request.html, "r") as f:
        content = f.read()
        soup = BeautifulSoup(content, "html.parser")
        dom = etree.HTML(str(soup))

        result = dom.xpath('//*[@id="protected-container"]/div[2]/div/ul/li/a')
        if len(result) != 1:
            request.send_command("message-error 'No uptobox link found'")
            exit(0)

        uptobox = result[0].text.strip()
        
        with open("/home/astrogoat/Documents/links.txt", "a") as l:
            l.write(uptobox + "\n")
            request.send_command("message-info 'Successfully append " + uptobox + " to links.txt'")

if __name__ == '__main__':
    main()
